# Generated by Django 2.2.7 on 2019-11-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garbage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garbage_name', models.CharField(max_length=20, verbose_name='垃圾名称')),
                ('garbage_bin', models.CharField(max_length=60, verbose_name='垃圾桶')),
                ('garbage_type', models.CharField(max_length=60, verbose_name='垃圾种类')),
            ],
            options={
                'db_table': 'garbage',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('News_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('sorces', models.CharField(max_length=50, verbose_name='来源')),
                ('photo', models.CharField(max_length=200, verbose_name='照片')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('topic', models.CharField(max_length=20, verbose_name='标签')),
                ('time', models.DateTimeField(max_length=20, verbose_name='时间')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='总浏览量')),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论ID')),
                ('user_name', models.CharField(blank=True, max_length=10, verbose_name='用户名')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('create_time', models.DateTimeField(verbose_name='创作时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('avatar', models.CharField(blank=True, max_length=45, null=True, verbose_name='头像')),
            ],
            options={
                'db_table': 'news_comment',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('username', models.CharField(blank=True, max_length=10, verbose_name='用户名')),
                ('e_mail', models.EmailField(blank=True, max_length=40, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='电话')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('salt', models.CharField(blank=True, max_length=45, null=True)),
                ('real_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名')),
                ('avatar', models.CharField(blank=True, max_length=200, null=True, verbose_name='头像')),
                ('user_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='简介')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
            options={
                'db_table': 'user_token',
            },
        ),
    ]
